/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.Person.Person;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
/**
 *
 * @author Administrator
 */
public class ManageUserAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageUserAccountJPanel
     */
    private JPanel container;
    private Enterprise enterprise;
    private Network network;

    public ManageUserAccountJPanel(JPanel container, Enterprise enterprise,Network network) {
        initComponents();
        this.enterprise = enterprise;
        this.container = container;

        popOrganizationComboBox();
       // employeeJComboBox.removeAllItems();
        popData();
    }

    public void popOrganizationComboBox() {
        organizationJComboBox.removeAllItems();

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationDirectory()) {
            organizationJComboBox.addItem(organization);
        }
    }
    
    public void populateEmployeeComboBox(Organization organization){
        employeeJComboBox.removeAllItems();
        
        for (Person person : organization.getPersonDirectory().getPersonDirectory()){
            employeeJComboBox.addItem(person);
        }
    }
    
    private void populateRoleComboBox(Organization organization){
        roleJComboBox.removeAllItems();
        for (Role role : organization.getSupportedRole()){
            roleJComboBox.addItem(role);
        }
    }

    public void popData() {

        DefaultTableModel model = (DefaultTableModel) userJTable.getModel();

        model.setRowCount(0);

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationDirectory()) {
            for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountDirectory()) {
                Object row[] = new Object[2];
                row[0] = ua;
                row[1] = ua.getRole();
                ((DefaultTableModel) userJTable.getModel()).addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g)
            {
                ImageIcon img=new ImageIcon("changeit.jpg");
                Image i=img.getImage();

                g.drawImage(i, 0, 0, this.getSize().width, this.getSize().height,this);

            }};
            jScrollPane1 = new javax.swing.JScrollPane();
            userJTable = new javax.swing.JTable();
            jLabel5 = new javax.swing.JLabel();
            organizationJComboBox = new javax.swing.JComboBox();
            jLabel3 = new javax.swing.JLabel();
            employeeJComboBox = new javax.swing.JComboBox();
            jLabel4 = new javax.swing.JLabel();
            roleJComboBox = new javax.swing.JComboBox();
            jLabel1 = new javax.swing.JLabel();
            nameJTextField = new javax.swing.JTextField();
            jLabel2 = new javax.swing.JLabel();
            passwordJTextField = new javax.swing.JTextField();
            createUserJButton = new javax.swing.JButton();
            backjButton1 = new javax.swing.JButton();

            setLayout(new java.awt.BorderLayout());

            jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            userJTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "User Name", "Role"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class
                };
                boolean[] canEdit = new boolean [] {
                    true, false
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
            jScrollPane1.setViewportView(userJTable);
            if (userJTable.getColumnModel().getColumnCount() > 0) {
                userJTable.getColumnModel().getColumn(0).setResizable(false);
                userJTable.getColumnModel().getColumn(1).setResizable(false);
            }

            jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 13, 375, 179));

            jLabel5.setText("Organization");
            jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 224, -1, -1));

            organizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
            organizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    organizationJComboBoxActionPerformed(evt);
                }
            });
            jPanel1.add(organizationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 221, 146, -1));

            jLabel3.setText("Employee");
            jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 264, -1, -1));

            employeeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
            jPanel1.add(employeeJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 261, 146, -1));

            jLabel4.setText("Role");
            jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 301, -1, -1));

            roleJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
            jPanel1.add(roleJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 301, 146, -1));

            jLabel1.setText("User Name");
            jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 341, -1, -1));
            jPanel1.add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 341, 146, -1));

            jLabel2.setText("Password");
            jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 385, -1, -1));
            jPanel1.add(passwordJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 382, 146, -1));

            createUserJButton.setText("Create");
            createUserJButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    createUserJButtonActionPerformed(evt);
                }
            });
            jPanel1.add(createUserJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 431, -1, -1));

            backjButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            backjButton1.setText("<< Back");
            backjButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    backjButton1ActionPerformed(evt);
                }
            });
            jPanel1.add(backjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

            add(jPanel1, java.awt.BorderLayout.CENTER);
        }// </editor-fold>//GEN-END:initComponents

    private void createUserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserJButtonActionPerformed
        String userName = nameJTextField.getText();
        String password = passwordJTextField.getText();
        Organization organization = (Organization) organizationJComboBox.getSelectedItem();
        Person person = (Person) employeeJComboBox.getSelectedItem();
        Role role = (Role) roleJComboBox.getSelectedItem();
        
        organization.getUserAccountDirectory().addUserAccount(userName, password, person, role);
        
        popData();
        JOptionPane.showMessageDialog(null, "Employee user account created successfully.");
        nameJTextField.setText("");
        passwordJTextField.setText("");
    }//GEN-LAST:event_createUserJButtonActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationJComboBoxActionPerformed
        Organization organization = (Organization) organizationJComboBox.getSelectedItem();
        if (organization != null){
            populateEmployeeComboBox(organization);
            populateRoleComboBox(organization);
        }
    }//GEN-LAST:event_organizationJComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JButton createUserJButton;
    private javax.swing.JComboBox employeeJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JTextField passwordJTextField;
    private javax.swing.JComboBox roleJComboBox;
    private javax.swing.JTable userJTable;
    // End of variables declaration//GEN-END:variables
}
