/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NurseRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.NurseOrganization;
import Business.Organization.PharmacyOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PharmacyRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import Business.WorkQueue.WorkRequest;

/**
 *
 * @author swarnadeekshitha
 */
public class RequestVaccineJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    //private Network network=new Network();
    private EcoSystem business;
    /**

    /**
     * Creates new form RequestVaccineJPanel
     */
    public RequestVaccineJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business=business;
        //this.network=network;
        
        
        VaccineComboBox.addItem("Hepatitis-B");
        VaccineComboBox.addItem("RotaVirus");
        VaccineComboBox.addItem("DTaP");
        VaccineComboBox.addItem("Influenza7");
        VaccineComboBox.addItem("Hib");
        VaccineComboBox.addItem("MMR");
        VaccineComboBox.addItem("Varicella");
        VaccineComboBox.addItem("Hepatitis A");
        VaccineComboBox.addItem("Meningococcal");
        VaccineComboBox.addItem("HPV");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g)
            {
                ImageIcon img=new ImageIcon("health logo12.jpg");
                Image i=img.getImage();

                g.drawImage(i, 0, 0, this.getSize().width, this.getSize().height,this);
            }

        };
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        VaccineComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        QuantityTxtField = new javax.swing.JTextField();
        SubmitBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Request for Vaccine from Pharmacy");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel1.setText("Vaccine Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 69, -1, -1));

        VaccineComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jPanel1.add(VaccineComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 58, 144, -1));

        jLabel2.setText("Quantity");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 129, -1, -1));
        jPanel1.add(QuantityTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 126, 139, -1));

        SubmitBtn.setText("Send Request");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SubmitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 190, 139, -1));

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:
        String message = VaccineComboBox.getSelectedItem().toString();
        int quantity = Integer.parseInt(QuantityTxtField.getText());
        
        PharmacyRequest request = new PharmacyRequest();
        request.setMessage(message);
        request.setQuantity(quantity);
        request.setSender(userAccount);
        request.setStatus("Vaccine requested");
       
        Enterprise ent=null;
        for(Enterprise newent : business.getNetworkList().get(0).getEnterpriseDirectory().getEnterpriseList()){
            if(newent instanceof PharmacyEnterprise){
             Organization org = new NurseOrganization();
        for (Organization organization : newent.getOrganizationDirectory().getOrganizationDirectory()){
            if (organization instanceof PharmacyOrganization){
                org = organization;
                break;
            }
        }
        System.out.println("org"+ org);
        if (org!=null){
            System.out.println("MESSAGE: " + message);
            WorkRequest r = userAccount.getWorkQueue().findRequest(message);
            if(r != null){
                System.out.println("didnt find request");
                int i = r.getQuantity();
                r.setQuantity(i+quantity);
                r.setStatus("Vaccine requested");
            }
            else{
            org.getWorkQueue().getWorkQueue().add(request);
            userAccount.getWorkQueue().getWorkQueue().add(request);
            }
        }
                JOptionPane.showMessageDialog(null, "Vaccine Request sent successfully.");
        }
        
        
       
            
        
       /** Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationDirectory()){
            System.out.println("org"+ organization);
            if (organization instanceof PharmacyOrganization){
                org = organization;
                System.out.println("org"+ org);
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkQueue().add(request);
            userAccount.getWorkQueue().getWorkQueue().add(request);
        }**/
        }
        
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        NurseWorkAreaJPanel dwjp = (NurseWorkAreaJPanel) component;
        dwjp.populateTable("", "");
        dwjp.populateVaccinationTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField QuantityTxtField;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JComboBox VaccineComboBox;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
